name: dry-publish

# Run on push only for main, if not it will trigger push & pull_request on PRs at the same time
on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
      - 'LICENSE'
      - 'renovate.json'
  pull_request:
    paths-ignore:
      - '*.md'
      - 'LICENSE'
      - 'renovate.json'
  workflow_dispatch:

env:
  CI: true

jobs:
  build:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: bash .github/workflows/setup.sh

      - run: pnpm run publish-all --dry
        id: publish_script
        env:
          GITHUB_EVENT_CLIENT_PAYLOAD: '{"branch": "main", "commit": "e2942655e5370b20e0b3942f4717c2a302b0b620"}'
          # https://docs.npmjs.com/generating-provenance-statements
          NPM_CONFIG_PROVENANCE: true
